### ISSUE TITLE
command 'extension.createp5project' not found

### ISSUE THREAD

**Issue by kartikay-bagla** [ProfAndreaPollini/vscode-p5-live-editor#1]
After installing and reloading VS Code, I created a p5.js project, proceeded to delete that project and then create another project. At which point I get this error. I have tried uninstalling and reinstalling the extension thrice (and of course reloading VS Code) but it doesn't seems to work.

**Comment by ProfAndreaPollini** [comment]
Thank you for the issue. I've fixed it, releasing 0.3.1 now :)

**Comment by ProfAndreaPollini** [comment]
new release here:
https://github.com/ProfAndreaPollini/vscode-p5-live-editor/releases/tag/0.3.1
