### ISSUE TITLE
Error loading projects.json file

### ISSUE THREAD

**Issue by Jaiiideep** [ProfAndreaPollini/vscode-p5-live-editor#2]
Error loading projects.json file
Source: p5js live editor (Extension)

Please Help
Thank you 👍

**Comment by ProfAndreaPollini** [comment]
it is strange, projects.json file is loaded on plugin startup. Without further information it would be difficult to dig into the problem. I will give it a try.

**Comment by ProfAndreaPollini** [comment]
I decide to remove the project management feature in 0.6.0. please upgrade.
